export interface Lesson {
  id: string
  title: string
  topic: string
  duration: number
  difficulty: "beginner" | "intermediate" | "advanced"
  thumbnail: string
  description: string
}

export const availableTopics = [
  { id: "python", name: "Python", icon: "🐍", color: "from-blue-500 to-cyan-500", category: "tech" },
  { id: "linux", name: "Linux", icon: "🐧", color: "from-yellow-500 to-orange-500", category: "tech" },
  { id: "javascript", name: "JavaScript", icon: "⚡", color: "from-yellow-400 to-yellow-600", category: "tech" },
  { id: "git", name: "Git & GitHub", icon: "📦", color: "from-orange-500 to-red-500", category: "tech" },
  { id: "sql", name: "SQL", icon: "🗄️", color: "from-green-500 to-teal-500", category: "tech" },
  { id: "react", name: "React", icon: "⚛️", color: "from-cyan-400 to-blue-500", category: "tech" },

  { id: "excel", name: "Excel", icon: "📊", color: "from-green-400 to-emerald-600", category: "business" },
  {
    id: "finanzas",
    name: "Finanzas Personales",
    icon: "💰",
    color: "from-emerald-500 to-teal-600",
    category: "business",
  },
  { id: "marketing", name: "Marketing Digital", icon: "📱", color: "from-pink-500 to-rose-600", category: "business" },
  {
    id: "productividad",
    name: "Productividad",
    icon: "⚡",
    color: "from-purple-500 to-indigo-600",
    category: "business",
  },

  { id: "photoshop", name: "Photoshop", icon: "🎨", color: "from-blue-600 to-purple-600", category: "creative" },
  { id: "writing", name: "Escritura Creativa", icon: "✍️", color: "from-amber-500 to-orange-600", category: "creative" },

  { id: "english", name: "Inglés", icon: "🇬🇧", color: "from-red-500 to-blue-500", category: "language" },
  { id: "spanish", name: "Español", icon: "🇪🇸", color: "from-yellow-500 to-red-600", category: "language" },
]

export const lessonsDatabase: Lesson[] = [
  {
    id: "py-variables-1",
    title: "Variables en Python - Nivel 1",
    topic: "python",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    description: "Aprende a declarar y usar variables básicas",
  },
  {
    id: "py-variables-2",
    title: "Variables en Python - Nivel 2",
    topic: "python",
    duration: 12,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    description: "Tipos de datos y conversiones",
  },
  {
    id: "py-variables-3",
    title: "Variables en Python - Nivel 3",
    topic: "python",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    description: "Variables avanzadas y scope",
  },
  {
    id: "py-functions-1",
    title: "Funciones en Python - Nivel 1",
    topic: "python",
    duration: 12,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Crea tus primeras funciones",
  },
  {
    id: "py-functions-2",
    title: "Funciones en Python - Nivel 2",
    topic: "python",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Parámetros y valores de retorno",
  },
  {
    id: "py-functions-3",
    title: "Funciones en Python - Nivel 3",
    topic: "python",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Funciones lambda y decoradores",
  },
  {
    id: "py-lists-1",
    title: "Listas - Nivel 1",
    topic: "python",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    description: "Crear y manipular listas básicas",
  },
  {
    id: "py-lists-2",
    title: "Listas - Nivel 2",
    topic: "python",
    duration: 12,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    description: "Métodos de listas y slicing",
  },
  {
    id: "py-lists-3",
    title: "Listas - Nivel 3",
    topic: "python",
    duration: 15,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    description: "List comprehensions avanzadas",
  },

  {
    id: "linux-intro-1",
    title: "Linux - Nivel 1",
    topic: "linux",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #fddb92 0%, #d1fdff 100%)",
    description: "Primeros pasos en Linux",
  },
  {
    id: "linux-intro-2",
    title: "Linux - Nivel 2",
    topic: "linux",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #fddb92 0%, #d1fdff 100%)",
    description: "Comandos esenciales de terminal",
  },
  {
    id: "linux-intro-3",
    title: "Linux - Nivel 3",
    topic: "linux",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #fddb92 0%, #d1fdff 100%)",
    description: "Administración de sistemas",
  },

  {
    id: "js-basics-1",
    title: "JavaScript - Nivel 1",
    topic: "javascript",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #ffeaa7 0%, #fdcb6e 100%)",
    description: "Variables y tipos de datos",
  },
  {
    id: "js-basics-2",
    title: "JavaScript - Nivel 2",
    topic: "javascript",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #ffeaa7 0%, #fdcb6e 100%)",
    description: "Funciones y arrays",
  },
  {
    id: "js-basics-3",
    title: "JavaScript - Nivel 3",
    topic: "javascript",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #ffeaa7 0%, #fdcb6e 100%)",
    description: "Programación asíncrona",
  },

  {
    id: "git-intro-1",
    title: "Git - Nivel 1",
    topic: "git",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)",
    description: "Primeros commits y repositorios",
  },
  {
    id: "git-intro-2",
    title: "Git - Nivel 2",
    topic: "git",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)",
    description: "Branches y merging",
  },
  {
    id: "git-intro-3",
    title: "Git - Nivel 3",
    topic: "git",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)",
    description: "Colaboración en GitHub",
  },

  {
    id: "sql-basics-1",
    title: "SQL - Nivel 1",
    topic: "sql",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #7bed9f 0%, #2ed573 100%)",
    description: "SELECT y WHERE básicos",
  },
  {
    id: "sql-basics-2",
    title: "SQL - Nivel 2",
    topic: "sql",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #7bed9f 0%, #2ed573 100%)",
    description: "JOINs y relaciones",
  },
  {
    id: "sql-basics-3",
    title: "SQL - Nivel 3",
    topic: "sql",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #7bed9f 0%, #2ed573 100%)",
    description: "Subconsultas y optimización",
  },

  {
    id: "react-intro-1",
    title: "React - Nivel 1",
    topic: "react",
    duration: 12,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #74b9ff 0%, #0984e3 100%)",
    description: "Componentes básicos",
  },
  {
    id: "react-intro-2",
    title: "React - Nivel 2",
    topic: "react",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #74b9ff 0%, #0984e3 100%)",
    description: "Props y estado",
  },
  {
    id: "react-intro-3",
    title: "React - Nivel 3",
    topic: "react",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #74b9ff 0%, #0984e3 100%)",
    description: "Hooks avanzados",
  },

  {
    id: "excel-intro-1",
    title: "Excel - Nivel 1",
    topic: "excel",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    description: "Navegación y formato básico",
  },
  {
    id: "excel-intro-2",
    title: "Excel - Nivel 2",
    topic: "excel",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    description: "Fórmulas esenciales",
  },
  {
    id: "excel-intro-3",
    title: "Excel - Nivel 3",
    topic: "excel",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    description: "Tablas dinámicas y macros",
  },

  {
    id: "fin-budget-1",
    title: "Finanzas - Nivel 1",
    topic: "finanzas",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)",
    description: "Crear tu primer presupuesto",
  },
  {
    id: "fin-budget-2",
    title: "Finanzas - Nivel 2",
    topic: "finanzas",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)",
    description: "Estrategias de ahorro efectivas",
  },
  {
    id: "fin-budget-3",
    title: "Finanzas - Nivel 3",
    topic: "finanzas",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)",
    description: "Inversión y planificación",
  },

  {
    id: "mkt-intro-1",
    title: "Marketing Digital - Nivel 1",
    topic: "marketing",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #ec4899 0%, #db2777 100%)",
    description: "Fundamentos del marketing digital",
  },
  {
    id: "mkt-intro-2",
    title: "Marketing Digital - Nivel 2",
    topic: "marketing",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #ec4899 0%, #db2777 100%)",
    description: "Redes sociales y contenido",
  },
  {
    id: "mkt-intro-3",
    title: "Marketing Digital - Nivel 3",
    topic: "marketing",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #ec4899 0%, #db2777 100%)",
    description: "SEO y analítica avanzada",
  },

  {
    id: "prod-time-1",
    title: "Productividad - Nivel 1",
    topic: "productividad",
    duration: 8,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
    description: "Gestión básica del tiempo",
  },
  {
    id: "prod-time-2",
    title: "Productividad - Nivel 2",
    topic: "productividad",
    duration: 12,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
    description: "Eliminar distracciones",
  },
  {
    id: "prod-time-3",
    title: "Productividad - Nivel 3",
    topic: "productividad",
    duration: 15,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
    description: "Sistemas de productividad avanzados",
  },

  {
    id: "ps-intro-1",
    title: "Photoshop - Nivel 1",
    topic: "photoshop",
    duration: 12,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)",
    description: "Interface y herramientas básicas",
  },
  {
    id: "ps-intro-2",
    title: "Photoshop - Nivel 2",
    topic: "photoshop",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)",
    description: "Capas y máscaras",
  },
  {
    id: "ps-intro-3",
    title: "Photoshop - Nivel 3",
    topic: "photoshop",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)",
    description: "Retoque fotográfico profesional",
  },

  {
    id: "write-basics-1",
    title: "Escritura Creativa - Nivel 1",
    topic: "writing",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)",
    description: "Fundamentos de escritura",
  },
  {
    id: "write-basics-2",
    title: "Escritura Creativa - Nivel 2",
    topic: "writing",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)",
    description: "Desarrollo de personajes",
  },
  {
    id: "write-basics-3",
    title: "Escritura Creativa - Nivel 3",
    topic: "writing",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)",
    description: "Diálogos y narrativa avanzada",
  },

  {
    id: "eng-basics-1",
    title: "Inglés - Nivel 1",
    topic: "english",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #ef4444 0%, #3b82f6 100%)",
    description: "Gramática y vocabulario básico",
  },
  {
    id: "eng-basics-2",
    title: "Inglés - Nivel 2",
    topic: "english",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #ef4444 0%, #3b82f6 100%)",
    description: "Conversación cotidiana",
  },
  {
    id: "eng-basics-3",
    title: "Inglés - Nivel 3",
    topic: "english",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #ef4444 0%, #3b82f6 100%)",
    description: "Inglés de negocios",
  },

  {
    id: "esp-basics-1",
    title: "Español - Nivel 1",
    topic: "spanish",
    duration: 10,
    difficulty: "beginner",
    thumbnail: "linear-gradient(135deg, #eab308 0%, #dc2626 100%)",
    description: "Fundamentos del español",
  },
  {
    id: "esp-basics-2",
    title: "Español - Nivel 2",
    topic: "spanish",
    duration: 15,
    difficulty: "intermediate",
    thumbnail: "linear-gradient(135deg, #eab308 0%, #dc2626 100%)",
    description: "Gramática española intermedia",
  },
  {
    id: "esp-basics-3",
    title: "Español - Nivel 3",
    topic: "spanish",
    duration: 18,
    difficulty: "advanced",
    thumbnail: "linear-gradient(135deg, #eab308 0%, #dc2626 100%)",
    description: "Español avanzado y literatura",
  },
]

export function getLessonsByTopic(topicId: string): Lesson[] {
  return lessonsDatabase.filter((lesson) => lesson.topic === topicId)
}

export function getAllLessonsForTopics(topicIds: string[]): Lesson[] {
  return lessonsDatabase.filter((lesson) => topicIds.includes(lesson.topic))
}
